-- DROP TABLE IF EXISTS intent
CREATE TABLE IF NOT EXISTS intent (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tag TEXT NOT NULL,
    pattern TEXT NOT NULL,
    response TEXT NOT NULL
);

-- DROP TABLE IF EXISTS intent
-- CREATE TABLE IF NOT EXISTS TABLE intent (
--     id INTEGER PRIMARY KEY AUTOINCREMENT,
--     created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     tag TEXT NOT NULL,
--     pattern TEXT NOT NULL,
--     response TEXT NOT NULL
-- );